name: flutter_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6 
  flutter_inappwebview: ^6.0.0
  image_picker: ^1.1.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
